# Generated by Django 5.2.10 on 2026-01-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='kategori_id',
            new_name='kategori',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='status_id',
            new_name='status',
        ),
    ]
